use_frameworks!

platform :ios, '10.0'

target 'ShortClipVideoTrimmerUI_Example' do
  pod 'ShortClipVideoTrimmerUI', :path => '../'

  target 'ShortClipVideoTrimmerUI_Tests' do
    inherit! :search_paths

    
  end
end
